apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.apiGateway.name | default "gpsd-api-gateway" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.apiGateway.name }}
spec:
  replicas: {{ .Values.deployments.apiGateway.replicas }}
  selector:
    matchLabels:
      app: gpsd-api-gateway
  template:
    metadata:
      labels:
        app: gpsd-api-gateway
    spec:
      containers:
      - name: gpsd-api-gateway
        image: "{{ .Values.deployments.apiGateway.image.repository }}:{{ .Values.deployments.apiGateway.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.apiGateway.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.apiGateway.port }}
          name: https
        volumeMounts:
          - name: certs
            mountPath: /etc/ssl/certs
            readOnly: true
        env:
        - name: NODE_ENV
          value: "{{ .Values.deployments.apiGateway.environment.NODE_ENV }}"
        - name: GPSD_API_GATEWAY_PORT
          value: "{{ .Values.deployments.apiGateway.environment.PORT }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.deployments.apiGateway.environment.secrets.JWT_SECRET }}
              key: "JWT_SECRET"
        - name: REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.deployments.apiGateway.environment.secrets.REFRESH_SECRET }}
              key: "REFRESH_SECRET"
      volumes:
        - name: certs
          secret:
            secretName: gpsd-api-gateway-certificates
      livenessProbe:
        httpGet:
          path: {{ .Values.deployments.apiGateway.livenessProbe.httpGet.path }}
          port: {{ .Values.deployments.apiGateway.port }}
        initialDelaySeconds: {{ .Values.deployments.apiGateway.livenessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.deployments.apiGateway.livenessProbe.periodSeconds }}
      readinessProbe:
        httpGet:
          path: {{ .Values.deployments.apiGateway.readinessProbe.httpGet.path }}
          port: {{ .Values.deployments.apiGateway.port }}
        initialDelaySeconds: {{ .Values.deployments.apiGateway.readinessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.deployments.apiGateway.readinessProbe.periodSeconds }}
  