apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpsd-incident-mgmt.fullname" . }}
  labels:
    {{- include "gpsd-incident-mgmt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gpsd-incident-mgmt.selectorLabels" . | nindent 4 }}
