apiVersion: apps/v1
kind: Deployment
metadata:
name: {{ .Values.apiGateway.name | default "gpsd-api-gateway" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.apiGateway.name }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: gpsd-api-gateway
  template:
    metadata:
      labels:
        app: gpsd-api-gateway
    spec:
      containers:
      - name: gpsd-api-gateway
        image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
        imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.apiGateway.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.apiGateway.environment.NODE_ENV }}"
        - name: GPSD_API_GATEWAY_PORT
          value: "{{ .Values.apiGateway.environment.PORT }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.apiGateway.environment.secrets.JWT_SECRET }}
              key: JWT_SECRET
        - name: REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.apiGateway.environment.secrets.REFRESH_SECRET }}
              key: REFRESH_SECRET
      livenessProbe:
        httpGet:
          path: {{ .Values.apiGateway.livenessProbe.httpGet.path }}
          port: {{ .Values.apiGateway.port }}
        initialDelaySeconds: {{ .Values.apiGateway.livenessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.apiGateway.livenessProbe.periodSeconds }}
      readinessProbe:
        httpGet:
          path: {{ .Values.apiGateway.readinessProbe.httpGet.path }}
          port: {{ .Values.apiGateway.port }}
        initialDelaySeconds: {{ .Values.apiGateway.readinessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.apiGateway.readinessProbe.periodSeconds }}
  