apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.evacMgmt.name | default "gpsd-evac-mgmt" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.evacMgmt.name }}
spec:
  replicas: {{ .Values.deployments.evacMgmt.replicas }}
  selector:
    matchLabels:
      app: gpsd-evac-mgmt
  template:
    metadata:
      labels:
        app: gpsd-evac-mgmt
    spec:
      containers:
      - name: gpsd-evac-mgmt
        image: "{{ .Values.deployments.evacMgmt.image.repository }}:{{ .Values.deployments.evacMgmt.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.evacMgmt.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.evacMgmt.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.deployments.evacMgmt.environment.NODE_ENV }}"
        - name: GPSD_EVAC_MGMT_PORT
          value: "{{ .Values.deployments.evacMgmt.environment.PORT }}"
        livenessProbe:
          httpGet:
            path: {{ .Values.deployments.evacMgmt.livenessProbe.httpGet.path }}
            port: {{ .Values.deployments.evacMgmt.port }}
            initialDelaySeconds: {{ .Values.deployments.evacMgmt.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployments.evacMgmt.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployments.evacMgmt.readinessProbe.httpGet.path }}
            port: {{ .Values.deployments.evacMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.evacMgmt.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.evacMgmt.readinessProbe.periodSeconds }}


