apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.incidentMgmt.name | default "gpsd-incident-mgmt" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.incidentMgmt.name }}
spec:
  replicas: {{ .Values.deployments.incidentMgmt.replicas }}
  selector:
    matchLabels:
      app: gpsd-incident-mgmt
  template:
    metadata:
      labels:
        app: gpsd-incident-mgmt
    spec:
      containers:
      - name: gpsd-incident-mgmt
        image: "{{ .Values.deployments.incidentMgmt.image.repository }}:{{ .Values.deployments.incidentMgmt.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.incidentMgmt.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.incidentMgmt.port }}
        env:
        - name: NODE_ENV
        value: "{{ .Values.deployments.incidentMgmt.environment.NODE_ENV }}"
        - name: GPSD_INCIDENT_MGMT_PORT
        value: "{{ .Values.deployments.incidentMgmt.environment.PORT }}"
        livenessProbe:
          httpGet:
          path: {{ .Values.deployments.incidentMgmt.livenessProbe.httpGet.path }}
          port: {{ .Values.deployments.incidentMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.incidentMgmt.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.incidentMgmt.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
          path: {{ .Values.deployments.incidentMgmt.readinessProbe.httpGet.path }}
          port: {{ .Values.deployments.incidentMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.incidentMgmt.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.incidentMgmt.readinessProbe.periodSeconds }}

