apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.mapMgmt.name | default "gpsd-map-mgmt" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.mapMgmt.name }}
spec:
  replicas: {{ .Values.deployments.mapMgmt.replicas }}
  selector:
    matchLabels:
      app: gpsd-map-mgmt
  template:
    metadata:
      labels:
        app: gpsd-map-mgmt
    spec:
      containers:
      - name: gpsd-map-mgmt
        image: "{{ .Values.deployments.mapMgmt.image.repository }}:{{ .Values.deployments.mapMgmt.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.mapMgmt.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.mapMgmt.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.deployments.mapMgmt.environment.NODE_ENV }}"
        - name: GPSD_MAP_MGMT_PORT
          value: "{{ .Values.deployments.mapMgmt.environment.PORT }}"
      livenessProbe:
        httpGet:
          path: {{ .Values.deployments.mapMgmt.livenessProbe.httpGet.path }}
          port: {{ .Values.deployments.mapMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.mapMgmt.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.mapMgmt.livenessProbe.periodSeconds }}
      readinessProbe:
        httpGet:
          path: {{ .Values.deployments.mapMgmt.readinessProbe.httpGet.path }}
          port: {{ .Values.deployments.mapMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.mapMgmt.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.mapMgmt.readinessProbe.periodSeconds }}

