apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.nginx.name | default "gpsd-nginx" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.nginx.name | default "gpsd-nginx" }}
spec:
  replicas: {{ .Values.deployments.nginx.replicas }}
  selector:
    matchLabels:
      app: gpsd-nginx
  template:
    metadata:
      labels:
        app: gpsd-nginx
    spec:
      containers:
      - name: gpsd-nginx
        image: "{{ .Values.deployments.nginx.image.repository }}:{{ .Values.deployments.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.nginx.image.pullPolicy }}
        ports:
        {{- range .Values.deployments.nginx.ports }}
        - containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.deployments.nginx.volumes.configMapName }}
        - name: certs
          secret:
            secretName: {{ .Values.deployments.nginx.volumes.certsSecretName }}
            items:
            {{- range .Values.deployments.nginx.volumes.certs }}
              - key: {{ .key }}
                path: {{ .path }}
            {{- end }}