apiVersion: v1
kind: ConfigMap
metadata:
    name: gpsd-nginx-config
    namespace: {{ .Values.global.namespace }}
    labels:
    app: gpsd-nginx
data:
    nginx.conf: |
        worker_processes 1;
        
        events {
            worker_connections 1024;
        }

        http {
            include       mime.types;
            default_type  application/octet-stream;

            sendfile        on;
            keepalive_timeout 65;

            # Redirect all HTTP traffic to HTTPS
            server {
                listen 80;
                server_name api.gpsd.com;

                location / {
                    return 301 https://$host$request_uri;
                }
            }

            # HTTPS Server
            server {
                listen 443 ssl;
                server_name api.gpsd.com;

                ssl_certificate /etc/nginx/certs/api.gpsd.com.crt;
                ssl_certificate_key /etc/nginx/certs/api.gpsd.com.key;

                location / {
                    proxy_pass https://gpsd-api-gateway:3000;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
        }