apiVersion: v1
kind: Secret
metadata:
    name: gpsd-nginx-certificates
    namespace: {{ .Values.global.namespace }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Files.Get .Values.certificates.nginx.certFile | b64enc }}
    tls.key: {{ .Files.Get .Values.certificates.nginx.keyFile | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
    name: gpsd-api-gateway-certificates
    namespace: {{ .Values.global.namespace }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Files.Get .Values.certificates.apiGateway.certFile | b64enc }}
    tls.key: {{ .Files.Get .Values.certificates.apiGateway.keyFile | b64enc }}