apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.sensorMgmt.name | default "gpsd-sensor-mgmt" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: gpsd-sensor-mgmt
spec:
  replicas: {{ .Values.deployments.sensorMgmt.replicas }}
  selector:
    matchLabels:
      app: gpsd-sensor-mgmt
  template:
    metadata:
      labels:
        app: gpsd-sensor-mgmt
    spec:
      containers:
      - name: gpsd-sensor-mgmt
        image: "{{ .Values.deployments.sensorMgmt.image.repository }}:{{ .Values.deployments.sensorMgmt.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.sensorMgmt.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.sensorMgmt.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.deployments.sensorMgmt.environment.NODE_ENV }}"
        - name: GPSD_SENSOR_MGMT_PORT
          value: "{{ .Values.deployments.sensorMgmt.environment.PORT }}"
        livenessProbe:
          httpGet:
            path: {{ .Values.deployments.sensorMgmt.livenessProbe.httpGet.path }}
            port: {{ .Values.deployments.sensorMgmt.port }}
            initialDelaySeconds: {{ .Values.deployments.sensorMgmt.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployments.sensorMgmt.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployments.sensorMgmt.readinessProbe.httpGet.path }}
            port: {{ .Values.deployments.sensorMgmt.port }}
            initialDelaySeconds: {{ .Values.deployments.sensorMgmt.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployments.sensorMgmt.readinessProbe.periodSeconds }}
