apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.userMgmt.name}}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.services.userMgmt.selector.app }}
  ports:
    {{- range .Values.services.userMgmt.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  type: {{ .Values.services.userMgmt.type }}
