apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.userMgmt.name | default "gpsd-user-mgmt" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployments.userMgmt.name }}
spec:
  replicas: {{ .Values.deployments.userMgmt.replicas }}
  selector:
    matchLabels:
      app: gpsd-user-mgmt
  template:
    metadata:
      labels:
        app: gpsd-user-mgmt
    spec:
      containers:
      - name: gpsd-user-mgmt
        image: "{{ .Values.deployments.userMgmt.image.repository }}:{{ .Values.deployments.userMgmt.image.tag }}"
        imagePullPolicy: {{ .Values.deployments.userMgmt.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployments.userMgmt.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.deployments.userMgmt.environment.NODE_ENV }}"
        - name: GPSD_USER_MGMT_PORT
          value: "{{ .Values.deployments.userMgmt.environment.PORT }}"
      livenessProbe:
        httpGet:
          path: {{ .Values.deployments.userMgmt.livenessProbe.httpGet.path }}
          port: {{ .Values.deployments.userMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.userMgmt.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.userMgmt.livenessProbe.periodSeconds }}
      readinessProbe:
        httpGet:
          path: {{ .Values.deployments.userMgmt.readinessProbe.httpGet.path }}
          port: {{ .Values.deployments.userMgmt.port }}
          initialDelaySeconds: {{ .Values.deployments.userMgmt.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployments.userMgmt.readinessProbe.periodSeconds }}
