name: Update Helm Values from Manifest

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change based on your repository setup

jobs:
  update-helm-values:
    runs-on: ubuntu-latest
    permissions:
        contents: write


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update values.yaml from input-manifest.yaml
        run: |
          # Read the image versions from input-manifest.yaml
          for service in $(yq eval '.images | keys | .[]' input-manifest.yaml); do
            TAG=$(yq eval ".images[\"$service\"]" input-manifest.yaml)
            
            # Convert input-manifest service names to Helm values.yaml format
            case "$service" in
              gpsd-api-gateway)       key="apiGateway";;
              gpsd-map-mgmt-svc)      key="mapMgmt";;
              gpsd-sensor-mgmt-svc)   key="sensorMgmt";;
              gpsd-user-mgmt-svc)     key="userMgmt";;
              gpsd-incident-mgmt-svc) key="incidentMgmt";;
              gpsd-evac-mgmt-svc)     key="evacMgmt";;
              *) echo "Unknown service: $service"; continue;;
            esac
            
            echo "Updating $key with tag $TAG"
            
            # Update the corresponding tag in values.yaml
            yq eval ".deployments.${key}.image.tag = \"$TAG\"" -i values.yaml
          done

      - name: Commit and Push Changes

        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add values.yaml
          git commit -m "Updated Helm values.yaml with new image tags" || echo "No changes to commit"
          git push origin main